services:
  lgtm:
    image: grafana/otel-lgtm:latest
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"

  ntfy:
      image: binwiederhier/ntfy:v2.22.0
      container_name: ntfy
      command:
        - serve
      ports:
        - "8085:80"
      volumes:
        - ./ntfy/cache:/var/cache/ntfy
      environment:
        NTFY_BASE_URL: http://localhost:8085
        NTFY_AUTH_DEFAULT_ACCESS: read-write