version: '3'

vars:
  APP: 'mycalendar'
  DOCKERFILE: 'Dockerfile'
  IMAGE_REG: 'ghcr.io/bruli'
  VERSION: '0.8.0'
  GOLANGCI_LINT_VERSION: 'v2.11.4'
  IMAGE_NAME: '{{.IMAGE_REG}}/{{.APP}}'
  CURRENT_IMAGE: '{{.IMAGE_NAME}}:{{.VERSION}}'
  DOCKER_COMPOSE: 'COMPOSE_BAKE=true docker compose'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  docker-up:
    desc: Start services with Docker Compose
    cmds:
      - echo "🚀 Starting services with Docker Compose..."
      - '{{.DOCKER_COMPOSE}} up -d --build'

  docker-down:
    desc: Stop and remove Docker Compose services
    cmds:
      - echo "🛑 Stopping and removing Docker Compose services..."
      - '{{.DOCKER_COMPOSE}} down'

  docker-ps:
    desc: Show active Docker Compose services
    cmds:
      - echo "📋 Active services:"
      - '{{.DOCKER_COMPOSE}} ps'

  fmt:
    desc: Format code with gofumpt
    cmds:
      - echo "👉 Formatting code with gofumpt..."
      - go tool gofumpt -w .

  security:
    desc: Check Go vulnerabilities
    cmds:
      - echo "👉 Check security"
      - go tool govulncheck ./...

  install-lint:
    desc: Install golangci-lint
    cmds:
      - echo "🔧 Installing golangci-lint {{.GOLANGCI_LINT_VERSION}}..."
      - go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@{{.GOLANGCI_LINT_VERSION}}

  lint:
    desc: Run golangci-lint
    deps:
      - install-lint
    cmds:
      - echo "🚀 Executing golangci-lint..."
      - golangci-lint run ./...

  clean:
    desc: Clean local artifacts
    cmds:
      - echo "🧹 Cleaning local artifacts..."
      - rm -rf bin dist coverage .*cache || true
      - go clean -testcache

  check:
    desc: Run format, lint and security checks
    deps:
      - fmt
      - lint
      - security
    cmds:
      - echo "✅ Format, linter and security success."

  docker-login:
    desc: Login into Docker registry
    cmds:
      - echo "🔐 Logging into Docker registry..."
      - echo "$CR_PAT" | docker login ghcr.io -u bruli --password-stdin

  docker-push-image:
    desc: Build and push Docker image
    deps:
      - docker-login
    cmds:
      - echo "🐳 Building and pushing Docker image {{.CURRENT_IMAGE}} ..."
      - |
        docker buildx build \
          --platform linux/arm64 \
          -t {{.CURRENT_IMAGE}} \
          -f {{.DOCKERFILE}} \
          --push \
          .
      - echo "✅ Image {{.CURRENT_IMAGE}} pushed successfully."
